kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: r.sbruder.de
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: r.sbruder.de/alertmanager-gotify
